services:
  netbox:
    image: netbox:latest-plugins
    pull_policy: never
    ports:
      - 9100:8080
    build:
      context: .
      dockerfile: Dockerfile-Plugins
  netbox-worker:
    image: netbox:latest-plugins
    pull_policy: never
